# Generated by Django 4.2.5 on 2023-10-19 05:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0004_rename_location_turf_locationid'),
        ('app', '0003_contact'),
    ]

    operations = [
        migrations.CreateModel(
            name='Checkout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('number', models.IntegerField(default=0)),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('turfid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userapp.turf')),
                ('userid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.register')),
            ],
        ),
    ]
