# Generated by Django 4.2.5 on 2023-10-30 04:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_checkout_comments'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkout',
            name='status',
            field=models.IntegerField(default=0),
        ),
    ]
