# Generated by Django 4.2.5 on 2023-10-25 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('managerapp', '0002_managerdata_delete_manregdata'),
    ]

    operations = [
        migrations.AddField(
            model_name='managerdata',
            name='status',
            field=models.IntegerField(default=0),
        ),
    ]
