# Generated by Django 4.2.5 on 2023-10-15 19:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Turf',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('image', models.ImageField(default='null.jpg', upload_to='image')),
                ('description', models.CharField(max_length=20)),
                ('price', models.IntegerField(default=0)),
                ('locationid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userapp.location')),
            ],
        ),
    ]
