# Generated by Django 4.2.5 on 2023-10-15 19:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0002_turf'),
    ]

    operations = [
        migrations.RenameField(
            model_name='turf',
            old_name='locationid',
            new_name='location',
        ),
    ]
