# Generated by Django 4.2.5 on 2023-10-15 19:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0003_rename_locationid_turf_location'),
    ]

    operations = [
        migrations.RenameField(
            model_name='turf',
            old_name='location',
            new_name='locationid',
        ),
    ]
