# Generated by Django 4.2.5 on 2023-10-25 05:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('managerapp', '0003_managerdata_status'),
        ('userapp', '0004_rename_location_turf_locationid'),
    ]

    operations = [
        migrations.AddField(
            model_name='turf',
            name='managerid',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='managerapp.managerdata'),
        ),
    ]
