# Generated by Django 4.2.5 on 2023-10-26 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0005_turf_managerid'),
    ]

    operations = [
        migrations.AddField(
            model_name='turf',
            name='status',
            field=models.IntegerField(default=0),
        ),
    ]
