# Generated by Django 4.2.7 on 2023-11-06 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0006_turf_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='turf',
            name='description',
            field=models.CharField(max_length=50),
        ),
    ]
